name: cd

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: docker lock rewrite
        run: |
          set -euo pipefail
          docker run -v "${PWD}":/run safewaters/docker-lock lock rewrite
          sudo chmod +r .devcontainer/Dockerfile
        shell: bash

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build images and push to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: true
          tags: mperel/dev-container:latest
          platforms: linux/amd64,linux/arm64
