name: ci-cd

on:
  push:
    branches: [ 'miperel/gh-actions' ]
  pull_request:
    branches: [ 'miperel/gh-actions' ]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: docker lock rewrite
        run: docker run -v "${PWD}":/run safewaters/docker-lock lock rewrite --tempdir .
        shell: bash

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

        # - name: login to dockerhub
        #   uses: docker/login-action@v1
        #   with:
        #     username: ${{ secrets.DOCKERHUB_SAFE_WATERS_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_SAFE_WATERS_PASSWORD }}

      - name: build images and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: false
          tags: mperel/dev-container:latest
          platforms: linux/amd64,linux/arm64
