name: ci

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: docker lock rewrite
        run: |
          set -euo pipefail
          docker run -v "${PWD}":/run safewaters/docker-lock lock rewrite --tempdir .
          sudo chmod +r .devcontainer/Dockerfile
        shell: bash

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build images and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: false
          tags: mperel/dev-container:latest
          platforms: linux/amd64,linux/arm64
