name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build images
        uses: docker/build-push-action@v4
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: false
          tags: mperel/dev-container:latest
          platforms: linux/amd64,linux/arm64
